

import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../models/line1_model.dart';

List<String> liine2name = [
'Al-Munib', 'Saqiyat Makki', 'Umm al-Masryeen', "Giza station", "Faisal", "Cairo University",
"Dokki", "research", "opera", "Sadat", "Muhammad Naguib", "Ataba", "Shuhada", "Massara", "Rawd al-Faraj",
"St. Teresa", "al-Khalafawi", "umbrellas", "Kolyet Alzseraa" , "Shubra Al Khaimah"
];
List<String> liine3name =[
  "Adly Mansour",
  "hikstep",
  "Omar bin al-khattab",
  "cape",
  "Hisham Barakat",
  "Picnic",
  "Nady Alshams",
  'Alf Maskan',
  "Heliopolis",
  "Aaron",
  "Pyramids",
  "Kolyet Albanat",
  "Ard Almaared",
  "Ard Almaared",
  "Abbasia",
  'Abdo Pasha',
  "Algesh",
  "Bab Alsheria",
  "Al Ataba",
  "Jamal Abdulnasser",
  "Maspero",
  "Safaa Hijazi",
  "kit kat" ,
];


 List<StationModel> STATIONLLIST=
 [
  StationModel(imagePath: 'assets/images/red_close.png', stationName: 'station1', stationNumber: 1 , lineNumber: 1 , color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station2', stationNumber: 2 , lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station3', stationNumber: 3, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station4', stationNumber: 4, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station5', stationNumber: 5, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station6', stationNumber: 6, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station7', stationNumber: 7, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station8', stationNumber: 8, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station9', stationNumber: 9, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station10', stationNumber: 10, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station11', stationNumber: 11, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station12', stationNumber: 12, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station13', stationNumber: 13, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station14', stationNumber: 14, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station15', stationNumber: 15, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station16', stationNumber: 16, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station17', stationNumber: 17, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station18', stationNumber: 18, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station19', stationNumber: 19, lineNumber: 1, color: Colors.red,isChangable: true , isChangableToLine2: true),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station20', stationNumber: 20, lineNumber: 1, color: Colors.red,isChangable: true , isChangableToLine3: true),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station21', stationNumber: 21, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station22', stationNumber: 22, lineNumber: 1, color: Colors.red,isChangable: true , isChangableToLine2: true),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station23', stationNumber: 23, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station24', stationNumber: 24, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station25', stationNumber: 25, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station26', stationNumber: 26, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station27', stationNumber: 27, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station28', stationNumber: 28, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station29', stationNumber: 29, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station30', stationNumber: 30, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station31', stationNumber: 31, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station32', stationNumber: 32, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station33', stationNumber: 33, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station34', stationNumber: 34, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_end.png', stationName: 'station35', stationNumber: 35, lineNumber: 1, color: Colors.red),




  StationModel(imagePath: 'assets/images/yellow-close-photo.png', stationName: 'station36', stationNumber: 36 , lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station37', stationNumber: 37 , lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station38', stationNumber: 38, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station39', stationNumber: 39, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station40', stationNumber: 40, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station41', stationNumber: 41, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station42', stationNumber: 42, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station43', stationNumber: 43, lineNumber: 2, color: Colors.yellow, isChangable: true , isChangableToLine1: true),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station44', stationNumber: 44, lineNumber: 2, color: Colors.yellow,isChangable: true , isChangableToLine3: true),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station45', stationNumber: 45, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station46', stationNumber: 46, lineNumber: 2, color: Colors.yellow,isChangable: true , isChangableToLine1: true),
   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station47', stationNumber: 47, lineNumber: 2, color: Colors.yellow),
   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station48', stationNumber: 48, lineNumber: 2, color: Colors.yellow),
   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station49', stationNumber: 49, lineNumber: 2, color: Colors.yellow),
   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station50', stationNumber: 50, lineNumber: 2, color: Colors.yellow),
   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station51', stationNumber: 51, lineNumber: 2, color: Colors.yellow),
   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station52', stationNumber: 52, lineNumber: 2, color: Colors.yellow),
   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station53', stationNumber: 53, lineNumber: 2, color: Colors.yellow),
   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station54', stationNumber: 54, lineNumber: 2, color: Colors.yellow),
   StationModel(imagePath: "assets/images/last_yellow.png", stationName: 'station55', stationNumber: 55, lineNumber: 2, color: Colors.yellow),


  StationModel(imagePath: 'assets/images/green_close.png', stationName: 'station56', stationNumber: 56 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station57', stationNumber: 57 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station58', stationNumber: 58 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station59', stationNumber: 59 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station60', stationNumber: 60 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station61', stationNumber: 61 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station62', stationNumber: 62 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station63', stationNumber: 63 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station64', stationNumber: 64 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station65', stationNumber: 65 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath:'assets/images/green_open.png', stationName: 'station66', stationNumber: 66 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station67', stationNumber: 67 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station68', stationNumber: 68 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station69', stationNumber: 69 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station70', stationNumber: 70 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station71', stationNumber: 71 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station72', stationNumber: 72 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station73', stationNumber: 73 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station74', stationNumber: 74 , lineNumber: 3, color: Colors.green, isChangable: true , isChangableToLine2: true),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station75', stationNumber: 75 , lineNumber: 3, color: Colors.green, isChangable: true , isChangableToLine1: true),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station76', stationNumber: 76 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station77', stationNumber: 77 , lineNumber: 3, color: Colors.green),
   StationModel(imagePath: 'assets/images/last_green.png', stationName: 'station78', stationNumber: 78, lineNumber: 3, color: Colors.green),

   StationModel(imagePath: '', stationName: 'station79', stationNumber: 79, secondStationNumber: 79,lineNumber: 3, color: Colors.green),
   StationModel(imagePath: '', stationName: 'station80', stationNumber: 80, secondStationNumber: 80,lineNumber: 3, color: Colors.green),
   StationModel(imagePath: '', stationName: 'station81', stationNumber: 81,secondStationNumber: 81, lineNumber: 3, color: Colors.green),
   StationModel(imagePath: '', stationName: 'station82', stationNumber: 82,secondStationNumber: 82, lineNumber: 3, color: Colors.green),
   StationModel(imagePath: '', stationName: 'station83', stationNumber: 83,secondStationNumber: 83, lineNumber: 3, color: Colors.green),

   StationModel(imagePath: '', stationName: 'station84', stationNumber: 79,secondStationNumber: 84, lineNumber: 3, color: Colors.green),
   StationModel(imagePath: '', stationName: 'station85', stationNumber: 80, secondStationNumber: 85,lineNumber: 3, color: Colors.green),
   StationModel(imagePath: '', stationName: 'station86', stationNumber: 81,secondStationNumber: 86, lineNumber: 3, color: Colors.green),
   StationModel(imagePath: '', stationName: 'station87', stationNumber: 82,secondStationNumber: 87, lineNumber: 3, color: Colors.green),
   StationModel(imagePath: '', stationName: 'station88', stationNumber: 83,secondStationNumber: 88, lineNumber: 3, color: Colors.green),



 ] ;

List<StationModel> STATIONLLISTWithLine3part1=
[
  StationModel(imagePath: 'assets/images/red_close.png', stationName: 'station1', stationNumber: 1 , lineNumber: 1 , color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station2', stationNumber: 2 , lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station3', stationNumber: 3, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station4', stationNumber: 4, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station5', stationNumber: 5, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station6', stationNumber: 6, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station7', stationNumber: 7, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station8', stationNumber: 8, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station9', stationNumber: 9, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station10', stationNumber: 10, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station11', stationNumber: 11, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station12', stationNumber: 12, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station13', stationNumber: 13, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station14', stationNumber: 14, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station15', stationNumber: 15, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station16', stationNumber: 16, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station17', stationNumber: 17, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station18', stationNumber: 18, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station19', stationNumber: 19, lineNumber: 1, color: Colors.red,isChangable: true , isChangableToLine2: true),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station20', stationNumber: 20, lineNumber: 1, color: Colors.red,isChangable: true , isChangableToLine3: true),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station21', stationNumber: 21, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station22', stationNumber: 22, lineNumber: 1, color: Colors.red,isChangable: true , isChangableToLine2: true),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station23', stationNumber: 23, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station24', stationNumber: 24, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station25', stationNumber: 25, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station26', stationNumber: 26, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station27', stationNumber: 27, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station28', stationNumber: 28, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station29', stationNumber: 29, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station30', stationNumber: 30, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station31', stationNumber: 31, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station32', stationNumber: 32, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station33', stationNumber: 33, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station34', stationNumber: 34, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_end.png', stationName: 'station35', stationNumber: 35, lineNumber: 1, color: Colors.red),




  StationModel(imagePath: 'assets/images/yellow-close-photo.png', stationName: 'station36', stationNumber: 36 , lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station37', stationNumber: 37 , lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station38', stationNumber: 38, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station39', stationNumber: 39, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station40', stationNumber: 40, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station41', stationNumber: 41, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station42', stationNumber: 42, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station43', stationNumber: 43, lineNumber: 2, color: Colors.yellow, isChangable: true , isChangableToLine1: true),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station44', stationNumber: 44, lineNumber: 2, color: Colors.yellow,isChangable: true , isChangableToLine3: true),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station45', stationNumber: 45, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station46', stationNumber: 46, lineNumber: 2, color: Colors.yellow,isChangable: true , isChangableToLine1: true),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station47', stationNumber: 47, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station48', stationNumber: 48, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station49', stationNumber: 49, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station50', stationNumber: 50, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station51', stationNumber: 51, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station52', stationNumber: 52, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station53', stationNumber: 53, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station54', stationNumber: 54, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: "assets/images/last_yellow.png", stationName: 'station55', stationNumber: 55, lineNumber: 2, color: Colors.yellow),


  StationModel(imagePath: 'assets/images/green_close.png', stationName: 'station56', stationNumber: 56 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station57', stationNumber: 57 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station58', stationNumber: 58 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station59', stationNumber: 59 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station60', stationNumber: 60 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station61', stationNumber: 61 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station62', stationNumber: 62 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station63', stationNumber: 63 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station64', stationNumber: 64 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station65', stationNumber: 65 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath:'assets/images/green_open.png', stationName: 'station66', stationNumber: 66 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station67', stationNumber: 67 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station68', stationNumber: 68 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station69', stationNumber: 69 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station70', stationNumber: 70 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station71', stationNumber: 71 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station72', stationNumber: 72 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station73', stationNumber: 73 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station74', stationNumber: 74 , lineNumber: 3, color: Colors.green, isChangable: true , isChangableToLine2: true),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station75', stationNumber: 75 , lineNumber: 3, color: Colors.green, isChangable: true , isChangableToLine1: true),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station76', stationNumber: 76 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station77', stationNumber: 77 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/last_green.png', stationName: 'station78', stationNumber: 78, lineNumber: 3, color: Colors.green),



  StationModel(imagePath: '', stationName: 'station84', stationNumber: 79,secondStationNumber: 84, lineNumber: 3, color: Colors.green),
  StationModel(imagePath: '', stationName: 'station85', stationNumber: 80, secondStationNumber: 85,lineNumber: 3, color: Colors.green),
  StationModel(imagePath: '', stationName: 'station86', stationNumber: 81,secondStationNumber: 86, lineNumber: 3, color: Colors.green),
  StationModel(imagePath: '', stationName: 'station87', stationNumber: 82,secondStationNumber: 87, lineNumber: 3, color: Colors.green),
  StationModel(imagePath: '', stationName: 'station88', stationNumber: 83,secondStationNumber: 88, lineNumber: 3, color: Colors.green),



] ;

List<StationModel> STATIONLLISTWithLine3part2=
[
  StationModel(imagePath: 'assets/images/red_close.png', stationName: 'station1', stationNumber: 1 , lineNumber: 1 , color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station2', stationNumber: 2 , lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station3', stationNumber: 3, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station4', stationNumber: 4, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station5', stationNumber: 5, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station6', stationNumber: 6, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station7', stationNumber: 7, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station8', stationNumber: 8, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station9', stationNumber: 9, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station10', stationNumber: 10, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station11', stationNumber: 11, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station12', stationNumber: 12, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station13', stationNumber: 13, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station14', stationNumber: 14, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station15', stationNumber: 15, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station16', stationNumber: 16, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station17', stationNumber: 17, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station18', stationNumber: 18, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station19', stationNumber: 19, lineNumber: 1, color: Colors.red,isChangable: true , isChangableToLine2: true),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station20', stationNumber: 20, lineNumber: 1, color: Colors.red,isChangable: true , isChangableToLine3: true),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station21', stationNumber: 21, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station22', stationNumber: 22, lineNumber: 1, color: Colors.red,isChangable: true , isChangableToLine2: true),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station23', stationNumber: 23, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station24', stationNumber: 24, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station25', stationNumber: 25, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station26', stationNumber: 26, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station27', stationNumber: 27, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station28', stationNumber: 28, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station29', stationNumber: 29, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station30', stationNumber: 30, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station31', stationNumber: 31, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station32', stationNumber: 32, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station33', stationNumber: 33, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_open.png', stationName: 'station34', stationNumber: 34, lineNumber: 1, color: Colors.red),
  StationModel(imagePath: 'assets/images/red_end.png', stationName: 'station35', stationNumber: 35, lineNumber: 1, color: Colors.red),




  StationModel(imagePath: 'assets/images/yellow-close-photo.png', stationName: 'station36', stationNumber: 36 , lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station37', stationNumber: 37 , lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station38', stationNumber: 38, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station39', stationNumber: 39, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station40', stationNumber: 40, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station41', stationNumber: 41, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station42', stationNumber: 42, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station43', stationNumber: 43, lineNumber: 2, color: Colors.yellow, isChangable: true , isChangableToLine1: true),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station44', stationNumber: 44, lineNumber: 2, color: Colors.yellow,isChangable: true , isChangableToLine3: true),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station45', stationNumber: 45, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station46', stationNumber: 46, lineNumber: 2, color: Colors.yellow,isChangable: true , isChangableToLine1: true),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station47', stationNumber: 47, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station48', stationNumber: 48, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station49', stationNumber: 49, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station50', stationNumber: 50, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station51', stationNumber: 51, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station52', stationNumber: 52, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station53', stationNumber: 53, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'station54', stationNumber: 54, lineNumber: 2, color: Colors.yellow),
  StationModel(imagePath: "assets/images/last_yellow.png", stationName: 'station55', stationNumber: 55, lineNumber: 2, color: Colors.yellow),


  StationModel(imagePath: 'assets/images/green_close.png', stationName: 'station56', stationNumber: 56 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station57', stationNumber: 57 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station58', stationNumber: 58 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station59', stationNumber: 59 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station60', stationNumber: 60 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station61', stationNumber: 61 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station62', stationNumber: 62 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station63', stationNumber: 63 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station64', stationNumber: 64 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station65', stationNumber: 65 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath:'assets/images/green_open.png', stationName: 'station66', stationNumber: 66 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station67', stationNumber: 67 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station68', stationNumber: 68 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station69', stationNumber: 69 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station70', stationNumber: 70 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station71', stationNumber: 71 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station72', stationNumber: 72 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station73', stationNumber: 73 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station74', stationNumber: 74 , lineNumber: 3, color: Colors.green, isChangable: true , isChangableToLine2: true),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station75', stationNumber: 75 , lineNumber: 3, color: Colors.green, isChangable: true , isChangableToLine1: true),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station76', stationNumber: 76 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/green_open.png', stationName: 'station77', stationNumber: 77 , lineNumber: 3, color: Colors.green),
  StationModel(imagePath: 'assets/images/last_green.png', stationName: 'station78', stationNumber: 78, lineNumber: 3, color: Colors.green),

  StationModel(imagePath: '', stationName: 'station79', stationNumber: 79, secondStationNumber: 79,lineNumber: 3, color: Colors.green),
  StationModel(imagePath: '', stationName: 'station80', stationNumber: 80, secondStationNumber: 80,lineNumber: 3, color: Colors.green),
  StationModel(imagePath: '', stationName: 'station81', stationNumber: 81,secondStationNumber: 81, lineNumber: 3, color: Colors.green),
  StationModel(imagePath: '', stationName: 'station82', stationNumber: 82,secondStationNumber: 82, lineNumber: 3, color: Colors.green),
  StationModel(imagePath: '', stationName: 'station83', stationNumber: 83,secondStationNumber: 83, lineNumber: 3, color: Colors.green),


] ;

List<StationModel> Line3Part1List=[
  StationModel(imagePath: '', stationName: 'station84', stationNumber: 79,secondStationNumber: 84, lineNumber: 3, color: Colors.green),
  StationModel(imagePath: '', stationName: 'station85', stationNumber: 80, secondStationNumber: 85,lineNumber: 3, color: Colors.green),
  StationModel(imagePath: '', stationName: 'station86', stationNumber: 81,secondStationNumber: 86, lineNumber: 3, color: Colors.green),
  StationModel(imagePath: '', stationName: 'station87', stationNumber: 82,secondStationNumber: 87, lineNumber: 3, color: Colors.green),
  StationModel(imagePath: '', stationName: 'station88', stationNumber: 83,secondStationNumber: 88, lineNumber: 3, color: Colors.green),


];
List<StationModel> Line3Part2List=[
  StationModel(imagePath: '', stationName: 'station79', stationNumber: 79, secondStationNumber: 79,lineNumber: 3, color: Colors.green),
  StationModel(imagePath: '', stationName: 'station80', stationNumber: 80, secondStationNumber: 80,lineNumber: 3, color: Colors.green),
  StationModel(imagePath: '', stationName: 'station81', stationNumber: 81,secondStationNumber: 81, lineNumber: 3, color: Colors.green),
  StationModel(imagePath: '', stationName: 'station82', stationNumber: 82,secondStationNumber: 82, lineNumber: 3, color: Colors.green),
  StationModel(imagePath: '', stationName: 'station83', stationNumber: 83,secondStationNumber: 83, lineNumber: 3, color: Colors.green),
];

 // List<StationModel> LINE2LIST =[
 //   StationModel(imagePath: 'assets/images/yellow-close-photo.png', stationName: 'Shubra Al Khaimah', stationNumber: 1 , lineNumber: 1),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'Kolyet Alzeraa', stationNumber: 2 , lineNumber: 2),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'AlMazalaat', stationNumber: 3, lineNumber: 3),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'al-Khalafawi', stationNumber: 4, lineNumber: 4),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'St. Teresa', stationNumber: 5, lineNumber: 5),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'Rawd al-Faraj', stationNumber: 6, lineNumber: 6),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'Massara', stationNumber: 7, lineNumber: 7),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'Shuhada', stationNumber: 8, lineNumber: 8),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'Ataba', stationNumber: 9, lineNumber: 9),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'Muhammad Naguib', stationNumber: 10, lineNumber: 10),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'Sadat', stationNumber: 46, lineNumber: 2),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'opera', stationNumber: 47, lineNumber: 2),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'Albohoth', stationNumber: 48, lineNumber: 2),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'Dokki', stationNumber: 49, lineNumber: 2),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'Cairo University', stationNumber: 50, lineNumber: 2),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'Faisal', stationNumber: 51, lineNumber: 2),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'Giza station', stationNumber: 52, lineNumber: 2),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'Umm al-Masryeen', stationNumber: 53, lineNumber: 2),
 //   StationModel(imagePath: 'assets/images/yellow-open-photo.png', stationName: 'Saqiyat Makki', stationNumber: 54, lineNumber: 2),
 //   StationModel(imagePath: "assets/images/last_yellow.png", stationName: 'Al-Munib', stationNumber: 55, lineNumber: 2),
 // ];

