
const Map<String, String> ar ={
  'appname':"المترو",

  'title app' :'المترو',

  //page1
  'page1addree':'تطبيق المترو' ,
  'page1miniAddree' :'ابدأ رحلة جديدة',
  'SETTINGS':'لاعدادات',
'BUTTONONEminiADDRESS':'محطة البداية',
'BUTTONONEmainADDRESS':' محطة البداية',
'BUTTONtwominiAffffDDRESS':'محطة الوصول',
'BUTTONtwomainADDRESS':'محطة الوصول',
'Calculate button':'احسب',
  'Description': 'بيساعدك تحدد نوع التذكرة اللي أنت محتاجها، ببساطة اختر المحطة اللي أنت فيها والمحطة اللي عايز توصل لها، هيحسب عدد المحطات اللي هاتعدي عليها ويحدد من خلالها نوع التذكرة اللي آنت محتاجها.',

  //page2
  'page2addrescurrent':'اختر محطة البداية' ,
  'page2addresend':'اختر محطة النهاية' ,
  'Search':'ابحث فى المحطات' ,
  'line1':'الخط الاول' ,
  'Line2':'الخط الثانى' ,
  'Line3':'الخط الثالث' ,
  //appname
  'label':'مترو',
//Page 3
'start station':'محطة البداية' ,
  'end station':'محطة الوصول' ,
  'trip details':'تفاصيل الرحلة' ,
  'number of stations':'عدد المحطات' ,
  'price of ticket':'سعر التذكرة' ,
  'time':'الوقت المتوقع' ,
  'pound':'ج.م' ,
  'minute':'دقيقة' ,
  'your ticket':'تذكرتك',
  'Yellow ticket':'التذكرة الصفراء',
  'Red ticket':'التذكرة الحمراء',
  'Green ticket':'التذكرة الخضراء',
  'blue ticket':'التذكرة الزرقاء',
  'Your Trip' : 'رحلتك',

// Drawer
'Start Trip':'بدء رحلة جديدة',
'Nearby station':'أقرب محطة',
'Metro Lines':'خطوط المترو',
'Tickets':'التذاكر',
'About Metro':'عن تطبيق المترو',
'About Developers':'عن المطورين',
'Change language':'تغيير اللغة',
'Help':'المساعدة',
  //change line
  'to line 1':'الى الخط الأول',
  'to line 2':'الى الخط الثانى',
  'to line 3':'الى الخط الثالث',
  'to Shobra Direction':'اتجاه شبرا الخيمة ( الخط الثانى )',
  'to Moneb':'اتجاه المنيب ( الخط الثانى )',
  'to Marg':'اتجاه المرج ( الخط الأول )',
  'to Helwan':'اتجاه حلوان ( الخط الأول )',
  'to Adly Mansour':'اتجاه عدلى منصور ( الخط الثالث )',
  'to Ataba':'اتجاه العتبة ( الخط الثالث )',
  'to kit kat Direction':"اتجاه الكيت كات ( الخط الثالث )",

//line 1 stations
  'station1':'حلوان',
  'station2':'عين حلوان',
  'station3':'جامعة حلوان',
  'station4':'وادى حوف',
  'station5':'حدائق حلوان',
  'station6':'المسرة',
  'station7':'طرة الأسمنت',
  'station8':'كوتسيكا',
  'station9':'طرة البلد',
  'station10':'ثكنات المعادى',
  'station11':'المعادى',
  'station12':'حدائق المعادى',
  'station13':'دار السلام',
  'station14':'الزهراء',
  'station15':'مارى جرجس',
  'station16':'الملك الصالح',
  'station17':'السيدة زينب',
  'station18':'سعد زغلول',
  'station19':'السادات',
  'station20':'جمال عبد الناصر',
  'station21':'أحمد عرابى',
  'station22':'الشهداء',
  'station23':'غمرة',
  'station24':'الدمرداش',
  'station25':'منشية الصدر',
  'station26':'كوبرى القبة',
  'station27':'حمامات القبة',
  'station28':'سرايا القبة',
  'station29':'حدائق الزيتون',
  'station30':'حلمية الزيتون',
  'station31':'المطرية',
  'station32':'عين شمس',
  'station33':'عزبة النخل',
  'station34':'المرج',
  'station35':'المرج الجديدة',

  //line 2 stations
  'station36':'شبرا الخيمة',
  'station37':'كلية الزراعة',
  'station38':'المظلات',
  'station39':'الخلفاوى',
  'station40':'سانت تريزا',
  'station41':'روض الفرج',
  'station42':'مسرة',
  'station43':'الشهداء',
  'station44':'العتبة',
  'station45':'محمد نجيب',
  'station46':'السادات',
  'station47':'الأوبرا',
  'station48':'الدقى',
  'station49':'البحوث',
  'station50':'جامعة القاهرة',
  'station51':'فيصل',
  'station52':'محطة الجيزة',
  'station53':'أم المصريين',
  'station54':'ساقية مكى',
  'station55':'المنيب',

  //line 3 stations
  'station56':'عدلى منصور',
  'station57':'هايكستب',
  'station58':'عمر بن الخطاب',
  'station59':'قباء',
  'station60':'هشام بركات',
  'station61':'النزهة',
  'station62':'نادى الشمس',
  'station63':'ألف مسكن',
  'station64':'هليوبليس',
  'station65':'هارون',
  'station66':'الأهرام',
  'station67':'كلية البنات',
  'station68':'الاستاد',
  'station69':'أرض المعارض',
  'station70':'العباسية',
  'station71':'عبده باشا',
  'station72':'الجيش',
  'station73':'باب الشعرية',
  'station74':'العتبة',
  'station75':'جمال عبد الناصر',
  'station76':'ماسبيرو',
  'station77':'صفاء حجازى',
  'station78':'الكيت كات',
  'station79':'السودان',
  'station80':'امبابة',
  'station81':'البوهى',
  'station82':'القومية العربية',
  'station83':'الطريق الدائرى',

  'station84':'التوفيقية',
  'station85':'وادى النيل',
  'station86':'جامعة الدول العربية',
  'station87':'بولاق الدكرور',
  'station88':'جامعة القاهرة',





};